# Generates rust_g.dm as a GitHub Actions Artifact
name: Generate DMSrc

on:
  push:
    branches: [ master , DMSrctest]
  pull_request:
    branches: [ master , DMSrctest]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        # Generate the actual .dm file.
        - uses: jannekem/run-python-script-action@v1
          with:
              script: |
                import glob
                import os
                import shutil

                os.chdir('dmsrc')

                outfilename = 'rust_g.dm'
                directory = glob.glob('*.dm')

                with open(outfilename, 'wb') as outfile:
                    for file in directory:
                        if file == outfilename:
                            # don't want to copy the output into the output
                            continue
                        with open(file, 'rb') as readfile:
                            shutil.copyfileobj(readfile, outfile)

        # Save the .dm file to Artifacts
        - uses: actions/upload-artifact@v3
          with:
              name: rust_g.dm
              path: /output/rust_g.dm


